#!/bin/bash

set -e

cd $(dirname $0)


# Enter the virtual environment
if [[ -d venv ]]; then
	. venv/bin/activate
else
	python3 -m venv venv
	. venv/bin/activate

	pip install -r requirements.txt
fi


# Start the server
set -x

export FLASK_APP=storeroom
export FLASK_DEBUG=1

flask run
